services:
  pw-app:
    image: pw-app
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run pageObjects-chrome
    volumes:
      - ./playwright-report:/app/playwright-report
      - ./test-results:/app/test-results
      - ./allure-report:/app/allure-report
    
